# Linux COE Package variables

OpenSUSE_15_Packages:
  - bind-utils
  - wget
  - lsb-release
  - bat
  - vim-data
  - net-snmp
  - nmap
  - openldap2-client

RedHat_8_Packages:
  - bind-utils
  - wget
  - net-snmp
  - net-snmp-utils
  - redhat-lsb-core
 
RedHat_9_Packages:
  - vim-enhanced
  - wget
  - net-snmp
  - net-snmp-utils
  - redhat-lsb-core
