---
# sub-task file for Linux COE
# filename: roles/COE/tasks/config_DNS.yml
#- name: Common Operating Environment - Configure Client DNS
#  hosts: all
#  user: rudebwoy
#  become_user: root
#  become: yes
#  become_method: sudo
#  vars_files:
#  - ../../../group_vars/COE.yml

  # Configure client DNS ...
  tasks:
  # Update /etc/resolv.conf
  - name: (OpenSUSE) Set DNS search list
    lineinfile:
      path: /etc/sysconfig/network/config
      regexp: '^NETCONFIG_DNS_STATIC_SEARCHLIST='
      line: NETCONFIG_DNS_STATIC_SEARCHLIST="yard.lo"
    when:
      - ansible_facts['distribution'] == "openSUSE Leap"
      - ansible_facts['distribution_major_version'] == "15"

  - name: (OpenSUSE) Set DNS servers
    lineinfile:
      path: /etc/sysconfig/network/config
      regexp: '^NETCONFIG_DNS_STATIC_SERVERS='
      line: NETCONFIG_DNS_STATIC_SERVERS="192.168.1.9"
    when:
      - ansible_facts['distribution'] == "openSUSE Leap"
      - ansible_facts['distribution_major_version'] == "15"

  - name: (OpenSUSE) Set DNS options
    lineinfile:
      path: /etc/sysconfig/network/config
      regexp: '^NETCONFIG_DNS_RESOLVER_OPTIONS='
      line: NETCONFIG_DNS_RESOLVER_OPTIONS="attempts:1 timeout:2"
    when:
      - ansible_facts['distribution'] == "openSUSE Leap"
      - ansible_facts['distribution_major_version'] == "15"

  - name: (OpenSUSE) Generate /etc/resolv.conf
    shell: netconfig update -f
    when:
      - ansible_facts['distribution'] == "openSUSE Leap"
      - ansible_facts['distribution_major_version'] == "15"

  - name: Copy /etc/resolv.conf (RHEL 8+ and clones)
    copy:
      src: ../files/resolv.conf
      dest: /etc/resolv.conf
      owner: root
      group: root
      mode: 0644
      backup: yes
    when:
      - ansible_facts['distribution'] == "RedHat"
      - ansible_facts['distribution_major_version'] == "8"

