---
# tasks file for Linux COE
# filename: roles/COE/tasks/main.yml
- name: Common Operating Environment
  hosts: all
  user: rudebwoy
  become_user: root
  become: yes
  become_method: sudo
  vars:
    ansible_python_interpreter: auto_silent
  vars_files:
  - ../../../group_vars/COE.yml

  # Install COE packages...
  tasks:
  # ...for OpenSUSE Leap 15 systems.
  - name: Install COE packages (OpenSUSE Leap 15)
    zypper: name={{ OpenSUSE_15_Packages }} state=installed
    when:
      - ansible_facts['distribution'] == "openSUSE Leap"
      - ansible_facts['distribution_major_version'] == "15"

  # ...for Red Hat Enterprise Linux 8 systems.
  - name: Install COE packages (RHEL 8 and clones)
    yum: name={{ RedHat_8_Packages }} state=installed
    when:
      - ansible_facts['distribution'] == "RedHat" or ansible_facts['distribution'] == "Rocky" or ansible_facts['distribution'] == "Alma"
      - ansible_facts['distribution_major_version'] == "8"

  # ...for Red Hat Enterprise Linux 9 systems.
  - name: Install COE packages (RHEL 9 and clones)
    yum: name={{ RedHat_9_Packages }} state=installed
    when:
      - ansible_facts['distribution'] == "RedHat" or ansible_facts['distribution'] == "Rocky" or ansible_facts['distribution'] == "Alma"
      - ansible_facts['distribution_major_version'] == "9"

  # Update all packages on RHEL 8+ systems.
  - name: Update all packages (RHEL 8+ and clones)
    dnf: name=* state=latest update_cache=yes
    when:
      - ansible_facts['distribution'] == "RedHat" or ansible_facts['distribution'] == "Rocky" or ansible_facts['distribution'] == "Alma"
      - ansible_facts['distribution_major_version'] >= "8"

#  # Update all packages on RHEL 8+ systems.
#  - name: Update all packages (RHEL 9 and clones)
#    dnf: name=* state=latest update_cache=yes
#    when:
#      - ansible_facts['distribution'] == "RedHat" or ansible_facts['distribution'] == "Rocky" or ansible_facts['distribution'] == "Alma"
#      - ansible_facts['distribution_major_version'] == "9"

  # Update all packages on OpenSUSE systems.
  - name: Update all packages (OpenSUSE)
    zypper: name=* state=latest update_cache=yes
    when:
      - ansible_facts['distribution'] == "openSUSE Leap"
      - ansible_facts['distribution_major_version'] == "15"

#  - name: (Red Hat) Install EPEL Repo
#  import_playbook: install_epel.yml
#  when:
#    - ansible_facts['distribution'] == "RedHat"
#    - ansible_facts['distribution_major_version'] == "8"
