---
# tasks file for wildfly
# filename: roles/wildfly/tasks/main.yml

- hosts: WildFly
  become_user: root
  become: yes
  become_method: sudo
  vars_files:
  - /home/witadmin/playbooks/inventories/staging/group_vars/wildfly.yml

  tasks:
  - name: Install JDK - {{ prod_jdk_version }}-headless
    dnf:
      name: "{{ prod_jdk_version }}-headless"

  - name: Template file to /etc/profile.d/env-java.sh
    template:
      src: ../templates/prod_env-java.sh.j2
      dest: /etc/profile.d/env-java.sh
      owner: root
      group: root
      mode: '0644'

  - name: Add wildfly system account and group
    user:
      name: wildfly
      #group: wildfly
      comment: "WildFly Service User Account"
      home: /home/wildfly
      shell: /bin/bash
      password: $6$mt7hvB7IsPbVP92G$hAXmASkv.8rHwT/h/MciLXUFZ7oP3sjUH3SjH85g/Q78OxqfN6tBTlVxn7qW6WFyRYCZBP62qWUN.ABjIcrsD1
      system: yes
      append: yes

  - name: Check if wildfly is installed
    stat: 
      path: /opt/wildfly/{{ prod_wildfly_version }}/jboss-modules.jar
      #checksum: b5376cd658b8dacb16f46e1819d0d437a20a8bd7
    register: wildfly_installed

#  - import_playbook: install.yml
#    when: stat_result.stat.exists == False

  - name: Create /opt/wildfly/{{ prod_wildfly_version }}
    file:
      path: /opt/wildfly/{{ prod_wildfly_version }}
      state: directory
      owner: wildfly
      group: wildfly
      mode: '0755'
    #when: stat_result.stat.exists == False

  - name: Extract wildfly-{{ prod_wildfly_version }}.tar.gz into /opt/wildfly/{{ prod_wildfly_version }}
    unarchive:
      src: ../files/wildfly-{{ prod_wildfly_version }}.tar.gz
      dest: /opt/wildfly/{{ prod_wildfly_version }}
      extra_opts: [--strip-components=1]
    when: wildfly_installed.stat.exists == False

  - name: Recursively change ownership of /opt/wildfly
    file:
      path: /opt/wildfly
      state: directory
      recurse: yes
      owner: wildfly
      group: wildfly
    when: wildfly_installed.stat.exists == False

  - name: Template file to /etc/profile.d/env-wildfly.sh
    template:
      src: ../templates/prod_env-wildfly.sh.j2
      dest: /etc/profile.d/env-wildfly.sh
      owner: root
      group: root
      mode: '0644'

  - name: Template file to /opt/wildfly/{{ prod_wildfly_version }}/bin/launch.sh
    template:
      src: ../templates/prod_launch.sh.j2
      dest: /opt/wildfly/{{ prod_wildfly_version }}/bin/launch.sh
      owner: wildfly
      group: wildfly
      mode: '0744'

  - name: Template file to /etc/systemd/system/wildfly.service
    template:
      src: ../templates/prod_wildfly.service.j2
      dest: /etc/systemd/system/wildfly.service
      owner: root
      group: root
      mode: '0644'

  - name: Copy file to /etc/sysconfig/wildfly
    copy:
      src: ../files/wildfly.sysconfig
      dest: /etc/sysconfig/wildfly
      owner: root
      group: root
      mode: '0644'

  - name: Reload systemd
    systemd:
      daemon_reload: yes

  - name: Enable and start wildfly
    systemd:
      name: wildfly
      state: started
      enabled: yes
      masked: no

#- import_playbook: install.yml
#- import_playbook: configure.yml

