- hosts: all
  user: rudebwoy
  #become: yes
  gather_facts: yes
  vars:
    ansible_python_interpreter: auto_silent
  
  tasks:
    - name: Ping
      ping:

    - name: Remote System Info
      debug:
        msg:
        - "Name: {{ ansible_user_gecos }}"
        - "User(UID,GID): {{ ansible_user_id }}({{ ansible_user_uid }},{{ ansible_user_gid }})"
        - "Home Directory: {{ ansible_user_dir }}"
        - "Shell: {{ ansible_user_shell }}"
        - "Kernel Version: {{ ansible_kernel }} {{ ansible_kernel_version }}"
        - "Distro: {{ ansible_distribution }} {{ ansible_distribution_major_version }} ({{ ansible_distribution_version}} {{ ansible_distribution_release }})"

